// Base colors
const BASE_COLORS = {
  // Brand Primary Colors - Your app's main colors
  PRIMARY: '',
  PRIMARY_DARK: '',
  PRIMARY_LIGHT: '',

  // Primary colors (original)
  BLUE_PRIMARY: '',
  BLUE_PRIMARY_DARK: '',
  BLUE_PRIMARY_LIGHT: '',

  // Secondary colors
  SECONDARY: '',
  SECONDARY_DARK: '',
  SECONDARY_LIGHT: '',

  // Neutrals
  BLACK: '#000000',
  DARK_GRAY: '#333333',
  GRAY: '#777777',
  LIGHT_GRAY: '#CCCCCC',
  EXTRA_LIGHT_GRAY: 'rgba(255, 255, 255, 0.10)',
  WHITE: '#FFFFFF',

  // Common UI colors

  TEXT_PRIMARY: '',
  TEXT_SECONDARY: '',
  TEXT_HINT: '#999999',
  DISABLED: '#CCCCCC',
  TRANSPARENT: 'transparent',
};

export const COLORS = {
  ...BASE_COLORS,

  // Functional colors
  BUTTON: {
    PRIMARY: BASE_COLORS.PRIMARY,
    PRIMARY_PRESSED: BASE_COLORS.PRIMARY_DARK,
    SECONDARY: BASE_COLORS.SECONDARY,
    SECONDARY_PRESSED: BASE_COLORS.SECONDARY_DARK,
    DISABLED: BASE_COLORS.DISABLED,
  },

  TEXT: {
    PRIMARY: BASE_COLORS.TEXT_PRIMARY,
    SECONDARY: BASE_COLORS.TEXT_SECONDARY,
    HINT: BASE_COLORS.TEXT_HINT,
    DISABLED: BASE_COLORS.DISABLED,
    INVERSE: BASE_COLORS.WHITE,
    LINK: BASE_COLORS.PRIMARY,
    BLACK: BASE_COLORS.BLACK,
    DARK_GRAY: BASE_COLORS.DARK_GRAY,
    GRAY: BASE_COLORS.GRAY,
    LIGHT_GRAY: BASE_COLORS.LIGHT_GRAY,
    EXTRA_LIGHT_GRAY: BASE_COLORS.EXTRA_LIGHT_GRAY,
  },
};

export default {
  COLORS,
};
